import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import localFont from 'next/font/local';

import Provider from '@/core/redux/provider';
import NowPlayingBar from './component/common/NowPlayingBar';
import './globals.css';

const raleway = Raleway({ subsets: ['latin'] });

const scratchy = localFont({
  src: '../../public/fonts/Scratchy.ttf',
  variable: '--font-scratchy',
});

// Font files can be colocated inside of `app`
const iosevka = localFont({
  // src: '../../public/fonts/iosevka/iosevka-medium.ttf',
  src: [
    {
      path: '../../public/fonts/iosevka/iosevka-thin.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iosevka/iosevka-light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iosevka/iosevka-regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iosevka/iosevka-medium.ttf',
      weight: '500',
      style: 'normal',
    },

    {
      path: '../../public/fonts/iosevka/iosevka-heavy.ttf',
      weight: '600',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-iosevka',
});

// Font files can be colocated inside of `app`
const satoshi = localFont({
  src: [
    {
      path: '../../public/fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Black.otf',
      weight: '900',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-satoshi',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${iosevka.variable} ${satoshi.variable} ${scratchy.variable}`}
      >
        <Provider>
          <div className="mb-10">{children}</div>
          <NowPlayingBar />
        </Provider>
      </body>
    </html>
  );
}
